In [73]:
import pandas as pd
from datetime import datetime

In [74]:
facturas=pd.DataFrame({'folio':(15234,
15235,
15236,
15237,
15238,
15239,
15240,
15241,
15242),
'sucursal':('CDMX01',
'MTY01',
'CDMX02',
'CDMX02',
'MTY01',
'GDL01',
'CDMX02',
'MTY01',
'GDL01'),
'monto':(1420.00,
1532.00,
890.00,
1300.00,
3121.47,
1100.5,
12230,
230.85,
1569),
'fecha':(datetime(2019,3,11,17,24),
datetime(2019,3,24,14,46),
datetime(2019,3,25,17,58),
datetime(2019,3,27,13,11),
datetime(2019,3,31,10,25),
datetime(2019,4,1,18,32),
datetime(2019,4,3,11,43),
datetime(2019,4,4,16,55),
datetime(2019,4,5,12,59)),
'cliente':(19234,
19232,
19235,
19233,
19236,
19237,
19232,
19233,
19232)
})
facturas

   folio sucursal     monto               fecha  cliente
0  15234   CDMX01   1420.00 2019-03-11 17:24:00    19234
1  15235    MTY01   1532.00 2019-03-24 14:46:00    19232
2  15236   CDMX02    890.00 2019-03-25 17:58:00    19235
3  15237   CDMX02   1300.00 2019-03-27 13:11:00    19233
4  15238    MTY01   3121.47 2019-03-31 10:25:00    19236
5  15239    GDL01   1100.50 2019-04-01 18:32:00    19237
6  15240   CDMX02  12230.00 2019-04-03 11:43:00    19232
7  15241    MTY01    230.85 2019-04-04 16:55:00    19233
8  15242    GDL01   1569.00 2019-04-05 12:59:00    19232

In [75]:
gastos_por_cliente=facturas.filter(items=["monto","cliente"])#´para filtrar por indicadores

In [76]:
gastos_por_cliente

      monto  cliente
0   1420.00    19234
1   1532.00    19232
2    890.00    19235
3   1300.00    19233
4   3121.47    19236
5   1100.50    19237
6  12230.00    19232
7    230.85    19233
8   1569.00    19232

In [77]:
clientes=gastos_por_cliente.groupby("cliente")
clientes

In [78]:
print(clientes.groups)#muestra donde se repiten esos valores

{19232: [1, 6, 8], 19233: [3, 7], 19234: [0], 19235: [2], 19236: [4], 19237: [5]}

In [79]:
for no_cliente,grupo in clientes:
  print("Grupo para clientes: ",no_cliente)
  print(grupo)
  print("-"* 50)

Grupo para clientes:  19232
     monto  cliente
1   1532.0    19232
6  12230.0    19232
8   1569.0    19232
--------------------------------------------------
Grupo para clientes:  19233
     monto  cliente
3  1300.00    19233
7   230.85    19233
--------------------------------------------------
Grupo para clientes:  19234
    monto  cliente
0  1420.0    19234
--------------------------------------------------
Grupo para clientes:  19235
   monto  cliente
2  890.0    19235
--------------------------------------------------
Grupo para clientes:  19236
     monto  cliente
4  3121.47    19236
--------------------------------------------------
Grupo para clientes:  19237
    monto  cliente
5  1100.5    19237
--------------------------------------------------

In [80]:
clientes.size()

cliente
19232    3
19233    2
19234    1
19235    1
19236    1
19237    1
dtype: int64

In [81]:
clientes.mean()

               monto
cliente
19232    5110.333333
19233     765.425000
19234    1420.000000
19235     890.000000
19236    3121.470000
19237    1100.500000

In [82]:
clientes.max()

            monto
cliente
19232    12230.00
19233     1300.00
19234     1420.00
19235      890.00
19236     3121.47
19237     1100.50

In [83]:
clientes.min()

           monto
cliente
19232    1532.00
19233     230.85
19234    1420.00
19235     890.00
19236    3121.47
19237    1100.50

In [2]:
import pandas as pd
import numpy as np

In [124]:
poblacion=pd.DataFrame({'Animal':('lobo','coyote','jaguar','cerdosalvaje',
'tapir','venado','ocelote','puma'),
'Norte_I':(12,np.nan,None,2,4,2,14,5),
'Norte_II':(23,4,25,21,9,121,1,2),
'Centro_I':(15,23,2,120,40,121,0,5),
'Sur_I':(28,46,14,156,79,12,2,np.nan)}).set_index('Animal')
poblacion

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
coyote            NaN         4        23   46.0
jaguar            NaN        25         2   14.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0
puma              5.0         2         5    NaN

In [11]:
poblacion.isna()#para saber si hay valores tipo Na

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo            False     False     False  False
coyote           True     False     False  False
jaguar           True     False     False  False
cerdosalvaje    False     False     False  False
tapir           False     False     False  False
venado          False     False     False  False
ocelote         False     False     False  False
puma            False     False     False   True

In [12]:
poblacion.isna().sum()#para saber cuantos nam hay por columna

Norte_I     2
Norte_II    0
Centro_I    0
Sur_I       1
dtype: int64

In [14]:
poblacion.isnull()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo            False     False     False  False
coyote           True     False     False  False
jaguar           True     False     False  False
cerdosalvaje    False     False     False  False
tapir           False     False     False  False
venado          False     False     False  False
ocelote         False     False     False  False
puma            False     False     False   True

In [15]:
poblacion.isnull().sum()

Norte_I     2
Norte_II    0
Centro_I    0
Sur_I       1
dtype: int64

In [18]:
poblacion.notna()#hace lo contrario .isna() me dice cuales no son nam

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             True      True      True   True
coyote          False      True      True   True
jaguar          False      True      True   True
cerdosalvaje     True      True      True   True
tapir            True      True      True   True
venado           True      True      True   True
ocelote          True      True      True   True
puma             True      True      True  False

In [21]:
poblacion.shape

(8, 4)

In [20]:
poblacion.notna().sum()#podemos observar que deberian estar 8 valores por columna pero no es asi

Norte_I     6
Norte_II    8
Centro_I    8
Sur_I       7
dtype: int64

In [22]:
poblacion.notnull()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             True      True      True   True
coyote          False      True      True   True
jaguar          False      True      True   True
cerdosalvaje     True      True      True   True
tapir            True      True      True   True
venado           True      True      True   True
ocelote          True      True      True   True
puma             True      True      True  False

In [26]:
poblacion.fillna(0)#Sirve para reemplazar todos los vlores tipo nam por el valor dentro del parentesis

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
coyote            0.0         4        23   46.0
jaguar            0.0        25         2   14.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0
puma              5.0         2         5    0.0

In [27]:
poblacion.fillna(15)

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
coyote           15.0         4        23   46.0
jaguar           15.0        25         2   14.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0
puma              5.0         2         5   15.0

In [31]:
poblacion.fillna("invalido")

               Norte_I  Norte_II  Centro_I     Sur_I
Animal
lobo              12.0        23        15      28.0
coyote        invalido         4        23      46.0
jaguar        invalido        25         2      14.0
cerdosalvaje       2.0        21       120     156.0
tapir              4.0         9        40      79.0
venado             2.0       121       121      12.0
ocelote           14.0         1         0       2.0
puma               5.0         2         5  invalido

In [44]:
poblacion1=poblacion['Norte_I'].dropna()#elimina las filas que contengan nam es bueno hacerlo cuando la base de datoes de muchisimas filas
poblacion1

Animal
lobo            12.0
cerdosalvaje     2.0
tapir            4.0
venado           2.0
ocelote         14.0
puma             5.0
Name: Norte_I, dtype: float64

In [62]:
promedio=int(sum(poblacion1)/len(poblacion1))#es mejor hacerlo creando otro dataframe par poder calcular el promedio ya qu elos valores tipo nan pueden afectar el rpmedio
poblacion["Norte_I"].fillna(promedio)

Animal
lobo            12.0
coyote           6.0
jaguar           6.0
cerdosalvaje     2.0
tapir            4.0
venado           2.0
ocelote         14.0
puma             5.0
Name: Norte_I, dtype: float64

Para identificar datos duplicados es .duplicated()

In [63]:
poblacion.duplicated()

Animal
lobo            False
coyote          False
jaguar          False
cerdosalvaje    False
tapir           False
venado          False
ocelote         False
puma            False
dtype: bool

In [65]:
otra_poblacion=pd.DataFrame({'Animal':('lobo','coyote','jaguar','cerdosalvaje',
'tapir','venado','ocelote','puma'),
'Norte_I':(12,4,None,2,4,2,14,4),
'Norte_II':(23,4,25,21,9,121,1,4),
'Centro_I':(15,4,2,120,40,121,0,4),
'Sur_I':(28,4,14,156,79,12,2,4)}).set_index('Animal')
otra_poblacion

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15     28
coyote            4.0         4         4      4
jaguar            NaN        25         2     14
cerdosalvaje      2.0        21       120    156
tapir             4.0         9        40     79
venado            2.0       121       121     12
ocelote          14.0         1         0      2
puma              4.0         4         4      4

In [66]:
otra_poblacion.duplicated()

Animal
lobo            False
coyote          False
jaguar          False
cerdosalvaje    False
tapir           False
venado          False
ocelote         False
puma             True
dtype: bool

In [68]:
otra_poblacion.drop_duplicates()#elimina el valor duplicado en este caso es puma

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15     28
coyote            4.0         4         4      4
jaguar            NaN        25         2     14
cerdosalvaje      2.0        21       120    156
tapir             4.0         9        40     79
venado            2.0       121       121     12
ocelote          14.0         1         0      2

In [88]:
poblacion.head()#muestra los primeros cinco datos o los que yo le escbriba en el parentesis

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
coyote            NaN         4        23   46.0
jaguar            NaN        25         2   14.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0

In [89]:
poblacion.tail()#muestrame los ultimos 5 datos

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0
puma              5.0         2         5    NaN

In [91]:
poblacion.isin(range(20,31))#para saber que valores estan dentro de ese rango de datos

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo            False      True     False   True
coyote          False     False      True  False
jaguar          False      True     False  False
cerdosalvaje    False      True     False  False
tapir           False     False     False  False
venado          False     False     False  False
ocelote         False     False     False  False
puma            False     False     False  False

In [92]:
poblacion.isin(range(20,31)).sum()

Norte_I     0
Norte_II    3
Centro_I    1
Sur_I       1
dtype: int64

In [107]:
poblacion.dropna()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0

In [114]:
poblacion

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0

In [112]:
poblacion.dropna(inplace=True)#aplica los metodos directamente sobre el data frame y la modifica permanentemente

In [113]:
poblacion

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0

In [118]:
poblacion.replace(np.nan,0)#Sirve para reemplazar valores (El que quiero reemplazar, el que lo va a reemplazar)

In [120]:
poblacion.replace(0,np.nan)

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23      15.0   28.0
coyote            NaN         4      23.0   46.0
jaguar            NaN        25       2.0   14.0
cerdosalvaje      2.0        21     120.0  156.0
tapir             4.0         9      40.0   79.0
venado            2.0       121     121.0   12.0
ocelote          14.0         1       NaN    2.0
puma              5.0         2       5.0    NaN

In [128]:
poblacion.replace([0,np.nan],"extinto",inplace=True)

In [129]:
poblacion.drop(["Centro_I"],axis=1)

              Norte_I  Norte_II    Sur_I
Animal
lobo             12.0        23     28.0
coyote        extinto         4     46.0
jaguar        extinto        25     14.0
cerdosalvaje      2.0        21    156.0
tapir             4.0         9     79.0
venado            2.0       121     12.0
ocelote          14.0         1      2.0
puma              5.0         2  extinto